### PR TITLE
Adding a config option to mask the request URI in analytics.

### PR DESCRIPTION
**Pull request by kevinswiber**

### CODE REVIEW

**Comment by dteirney** [comment]
Hi @kevinswiber,

Is it possible to also specify the mask string that is used?

This capability is very important for our solutions, and we'll be writing a separate Analytics report that will ultimately trigger a security event if ANY path or request URI within the Apigee analytics store is not masked.

That report will be easier to write if we can guarantee what the mask string is. Currently, we are masking the request URI and query parameters to blank strings for Edge Cloud API Proxies rather than a string of stars. Alternatively, our report could check for it being anything other than "whatever mask string we are using for the masking for both Edge Cloud API Proxies and Microgateway".

**Comment by kevinswiber** [comment]
Sure. I can make that change.

**Comment by jaskarangump** [comment]
Hi @kevinswiber, 
Is it possible to make the fields to be masked as configurable. Right now, we need only the two fields, but in future more fields might be logged into analytics from edgemicro and we might have to mask one of those.

**Comment by kevinswiber** [comment]
@jaskarangump Yes.  @srinandan had some input on this, as well.  This PR really just serves as a starting point.  The complexity of this feature is on a sliding scale, depending on how configurable we make it.  I started with the easiest possible option.  Happy to entertain more requirements.

@srinandan Feel free to add your thoughts to this PR, as well.

**Comment by srinandan** [comment]
@jaskarangump - I don't think we'd want to mask any more fields. I can think of two reasons for this:
1: Feature parity with Apigee Edge
2: Analytics is not an optional plugin. Basic analytics should always be captured. 

@dteirney - There are two fields in question here - URI and Path. I agree that should allow for the path to be fully masked. However, I think we should not fully mask URI. If masking is turned on, then I think URI should still contain protocol + hostname. Even during a TLS handshake, this information is available. From an analytics point of view, this can be an important field.

**Comment by srinandan** [comment]
I'd like to explain my earlier point with an example

The current request object (sent to analytics) contains:
`    request_uri:                      (req.protocol || 'http') + '://' + req.headers.host + req.url,
    request_path:                     req.url.split('?')[0]
`

Let's take the example `http://localhost:8080/api?queryparam=123`

Before masking: 
`request_uri` -> `http://localhost:8080/api?queryparam=123`
'request_path` -> `/api`

Current PR (after masking is turned on):
`request_uri` -> `****`
`request_path` -> `****`

My proposal:
`request_uri` -> `http://localhost:8080/****`
`reqesut_path` -> `****`

In this proposal, we preserve the protocol and host. I think that is important analytics information.

**Comment by jaskarangump** [comment]
@srinandan - We might want to mask more fields like target_url. I think it is not being sent to analytics from edgemicro. But can we confirm that it never will be?
Also, I am concerned about fields like target_basepath and proxy_basepath.

**Comment by srinandan** [comment]
Target information is not currently captured. In the future, if we do capture other fields that can contain sensitive data, we will also provide the ability to mask those fields.

Proxy_basepath is the same as request_path and we are providing the ability to mask that.

**Comment by dteirney** [comment]
@srinandan I'm happy with that proposal. @jaskarangump are we able to do the same for the configuration we have in Edge Cloud? I'd like the analytics data to more or less look the same for Cloud vs Microgateway customers.

**Comment by jaskarangump** [comment]
@dteirney - We would need to see how we can update the swagger to api utility. Nuking it is easier. However for this transformation we will need to have custom JS policies.

**Comment by dteirney** [comment]
@jaskarangump thanks. @srinandan in that case I'm not sure we'd end up using that approach.

Thinking more in this, wouldn't the protocol and domain be the same for every single response in Analytics? If so, why is having that information still useful?

**Comment by dteirney** [comment]
Commit as it exists would work for us as long as we can additionally configure the mask.

**Comment by kevinswiber** [comment]
Maybe there's a compromise.

```yaml
analytics:
  mask:
    output: '****' # This is the replacement text, configurable, default '****'.
    uri: true # Would mask the entire URI: scheme, host, path, query parameters, default false. Overrides more specific config options.
    scheme: true # Would mask the URI scheme, default false.
    host: true # Would mask the host (hostname:port), default false.
    path: true # Would mask the path (/hello/world), default false.
    queryParams: true # Would mask the query parameters
```

Adjacent options would be collapsed.  For example, if `path` and `queryParams` were set to true, only one mask would show (e.g., `https://example.com/hello?name=Kevin` would be masked as: `https://example.com/****`).

@srinandan @dteirney @jaskarangump Thoughts?

**Comment by jaskarangump** [comment]
@kevinswiber if we say scheme:false and host:false, will the output be ****://****/**** or ****

**Comment by jaskarangump** [comment]
I guess we want to find one pattern and check it is always that to ensure there is no extra information being leaked. This will make the patterns different based on whether a request has query params or not.

**Comment by jaskarangump** [comment]
We are fine with just
```
analytics:
  mask:
    output: '****'
```

**Comment by kevinswiber** [comment]
@dteirney @jaskarangump @srinandan 

I'm not inclined to merge the PR as-is.  This was a strawman to begin discussions.  To accomplish what you're doing today, you'd have to take an approach similar to what's possible with Edge Cloud.  

If you use a plugin in the microgateway, you can change the `req.url` value to a blank string or whatever mask value you like.  You can also do the same with `req.headers.host` to mask the host.

Example plugin:

```js
module.exports.init = function(config, logger, stats) {
  return {
    onend_response: function(req, res, data, next) {
      req.url = '';
      next(null, null);
    }
  };
}
```

@srinandan will follow up once we have a better plan for analytics masking.

**Comment by jaskarangump** [comment]
@kevinswiber - Hope you are well.
We had a look at https://github.com/apigee-127/volos/blob/master/analytics/apigee/lib/apigeeanalytics.js
to see which fields are being logged into analytics.

We primarily wanted to suppress the following values flowing into analytics - request_uri, request_path & proxy_pathsuffix

I couldn't find proxy_pathsuffix being set. But even if it is later added, it might be derived from req.url.
So if we mask that in a plugin, it should take care of all cases. 

Can you please confirm that this understanding is correct.

@srinandan, @dteirney  CC

**Comment by kevinswiber** [comment]
CCing @mdobson and @F1ERRO.  They will assist with follow-up.

**Comment by jaskarangump** [comment]
@mdobson  / @F1ERRO  - Can you please confirm the above point?
@srinandan CC

**Comment by mdobson** [comment]
`proxy_pathsuffix` is not being set in any microgateway code paths that I can see.

**Comment by jaskarangump** [comment]
@mdobson - Ya, we are ok with those, since they are not sent. So, only request_uri and request_path

**Comment by mdobson** [comment]
Ah. Then yes. A new configuration for the analytics plugin is probably
needed.

*--*
*Matthew Dobson* | *apigee <https://apigee.com/>* | m: +1.734.634.5472 |
twitter @mdobs <http://twitter.com/mdobs> @apigee
<https://twitter.com/apigee> | *Apigee Community
<http://community.apigee.com/>* for answers, ideas and support!

**Pull request closed without merging**
