### PR TITLE
Mask specific fields

### PR DESCRIPTION
**Pull request by mdobson**
An alternative approach to masking.

### CODE REVIEW

**Comment by jaskarangump** [comment]
@mdobson - Can you provide any indication when this feature will be released.

**Comment by mdobson** [comment]
Hi @jaskarangump 

@srinandan Can give some more light to what's going on. However, we're evaluating my approach to this internally. Essentially ensuring there isn't something easier or more edgemicro agnostic that can be done. Apologies that this is taking longer than anticipated.

-Matt

**Comment by mdobson** [comment]
So we'll be releasing the masking ability for request urls and paths on Friday March 3rd. 

Would you be able to elaborate on what the goal is with masking the access token?

-Matt

**Comment by jaskarangump** [comment]
@mdobson. The access token will be JWT for edge micro. And contains 'sub' field with username. 
We have a compliance requirement to not store unencrypted user information in analytics.

Thanks 
Jaskaran

**Comment by srinandan** [comment]
@jaskarangump, no part of the JWT is stored in the analytics database (that doesn't already exist). Looks like these are custom fields added to the JWT. They are not stored.

**Comment by jaskarangump** [comment]
OK. So, which access token is stored from edgemicro to analytics?

**Comment by srinandan** [comment]
Analytics for EM does not store any access token. Remember the access token for EM is a JWT. That contains information like developer, prod, app - things the analytics system already knows. This is just helping analytics increase the count, calc response times etc.

**Comment by mdobson** [comment]
We use the information in the JWT to determine things like the developer, product, proxy and app. The token itself and custom fields aren't store in analytics. Just the fields that the platform would know about anyway since it issued the key.

-Matt

**Comment by jaskarangump** [comment]
OK. Awesome. Thanks for that clarification. In that case we should be fine without it.

**Comment by mdobson** [comment]
👍 Expect this to go out this upcoming friday then.

**Comment by mdobson** [comment]
This is released please check out using `npm install edgemicro@2.4.0-beta`

**Comment by jaskarangump** [comment]
@mdobson - We tried this and this configuration is working fine for request_path.
However it is not masking request_uri. Instead when we add that configuration, it adds another field (request_url) to the payload sent to analytics and masks it. Please see below for details - 


With only path masked. i.e
analytics:
  mask_request_path: 'pathmask'
{
        "records": [{
                "client_received_start_timestamp": 1489012345851,
                "client_received_end_timestamp": 1489012345852,
                "recordType": "APIAnalytics",
                "apiproxy": "edgemicro_actor",
                "request_uri": "http://localhost:8000/actor/current",
                "request_path": "pathmask",
                "request_verb": "GET",
                "client_ip": "::1",
                "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
                "apiproxy_revision": "436",
                "response_status_code": 401,
                "client_sent_start_timestamp": 1489012345853,
                "client_sent_end_timestamp": 1489012345854
        }]
}
With both fields mask. i.e
analytics:
  mask_request_path: 'pathmask'
  mask_request_url: 'urlmask'
{
        "records": [{
                "client_received_start_timestamp": 1489012414594,
                "client_received_end_timestamp": 1489012414595,
                "recordType": "APIAnalytics",
                "apiproxy": "edgemicro_actor",
                "request_uri": "http://localhost:8000/actor/current",
                "request_path": "pathmask",
                "request_verb": "GET",
                "client_ip": "::1",
                "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
                "apiproxy_revision": "436",
                "response_status_code": 401,
                "client_sent_start_timestamp": 1489012414602,
                "client_sent_end_timestamp": 1489012414603,
                "request_url": "urlmask"
        }]
}

**Comment by mdobson** [comment]
verified. I can see where the issue is stemming as well. I'll get a fix and deploy something by friday to get you unblocked. Apologies for the issues on this, and thanks for your patience.

**Comment by mdobson** [comment]
PR Here: https://github.com/apigee/microgateway-plugins/pull/34

**Comment by mdobson** [comment]
try it at `npm install edgemicro@2.4.1-beta` I've pushed a small version increase to fix this issue for you.

**Comment by jaskarangump** [comment]
@mdobson - Is it pushed? Nothing is happening when I try npm installing this version

**Comment by jaskarangump** [comment]
Thanks @mdobson . I tried this and seems to be working as expected.
Is it possible to get final version of 2.4.1 soon? We have a customer deployment coming up pretty soon.

**Comment by jaskarangump** [comment]
@mdobson - Can you let us know when the final version is planned to be released.

**Comment by mdobson** [comment]
I can look at cutting a release in the next two weeks for this plugin update. Does that work?

**Comment by mdobson** [comment]
I'll be releasing this tomorrow AM EST.

**Comment by mdobson** [comment]
@jaskarangump ^^

**Comment by mdobson** [comment]
I've pushed a release with this plugin bug fix in it. Can be found at `npm install edgemicro@2.3.5`.

This is the only addition in that version of edgemicro.

**Comment by jaskarangump** [comment]
Thanks @mdobson

**Pull request merged**
